chore(deps): rollback to kafka 2.6.1
This error happen randomly, and can't explain it for now, maybe wait that the `exactly_once_beta` leave the beta
```
org.apache.kafka.streams.errors.StreamsException: Exception caught during initialization of GlobalStreamThread
	at org.apache.kafka.streams.processor.internals.GlobalStreamThread.initialize(GlobalStreamThread.java:421)
	at org.apache.kafka.streams.processor.internals.GlobalStreamThread.run(GlobalStreamThread.java:287)
Caused by: org.apache.kafka.common.errors.TimeoutException: Global task did not make progress to restore state within 300000 ms. Adjust `task.timeout.ms` if needed
```